### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jo-mueller** [jo-mueller/napari-vedo-bridge#12]
@marcomusy 

Hi Marco,
I was wondering whether we should do an early release of the plugin to pypi once the currently pending PRs are merged? I think with the new boxcutter in place it's already very helpful and cool :)

**Comment by marcomusy** [comment]
Hi Johannes, yes! it already works kind of nicely!
Maybe the name can be more general as in the future we could add functionalities that go beyond meshes and cutting (point clouds, 3d images etc)

**Comment by marcomusy** [comment]
Hi again 
I boldly merged the stuff i've done, which includes all the 3 cutters.
It seems to work well now!
End of this week I will make a new vedo release.

**Comment by jo-mueller** [comment]
Hi @marcomusy ,

with the new vedo version released, do you mind if I release the plugin in its current state? :)

**Comment by marcomusy** [comment]
Yes, maybe we can find a better name than MeshCutter (although we can change it later on?), as this might be more general than a cutting functionality.

**Comment by marcomusy** [comment]
Sounds good to me.
